woowacourse-teams/2025-routie

backend/spring-routie/.github/workflows/discord-notification.yml
=> chore: Discord PR 알람 기능 추가

frontend/src/@common/components/Flex/Flex.style.ts, frontend/src/@common/components/Flex/Flex.tsx
Flex 박스를 담당할 컴포넌트 구현
추후에 스토리북 구현 필요
close #16
=> feat: Flex 컴포넌트 구현

.github/workflows/setup-open-issue.yml
Issue 사이드바의 많은 정보를 수기로 입력하고 있음
Issue 사이드바 자동 설정을 통해 작업 생산성 향상
빈 Issue를 생성하면 사이드바에 디폴트 값을 자동으로 작성해줌
- 정책
- Issue 생성자 기반 라벨 부여
- Issue 생성자가 백엔드 팀원이면 `backend` 라벨 부여
- Issue 생성자가 백엔드 팀원이면 `frontend` 라벨 부여
- Issue 제목 기반 작업 타입 라벨 부여
- '[TEST]': 'test'
- '[FEATURE]': 'feature'
- '[FIX]': 'fix'
- '[STYLE]': 'style'
- '[DOCS]': 'docs'
- '[CHORE]': 'chore'
- '[REFACTOR]': 'refactor'
- Sprint: 오늘에 해당하는 iteration 선택
- Status: `Todo`로 설정
- Start date: 오늘로 설정
- Hierarchy: `task`로 설정
close #27
=> chore: Issue 사이드바 자동 설정 기능 추가

.github/pull_request_template.md
일반적으로 PR이 merge되면 Issue도 close됩니다.
이를 PR 의 `Closes #{이슈번호}`로 자동화할 수 있습니다.
그러나, 현재 PR 템플릿에는 해당 옵션이 존재하지 않습니다.
PR 템플릿의 하단에 Closes #{이슈번호} 형식의 템플릿을 추가합니다.
```md
```
main 브랜치에 직접 merge 합니다.
develop 브랜치와 관련 없기 때문입니다.
=> chore: PR 템플릿에 Closes 옵션 추가

frontend/src/@common/components/Button/Button.style.ts, frontend/src/@common/components/Button/Button.tsx
button 공통 컴포넌트 구현
추후 스토리북 구현 필요
close #19
=> feat: button 컴포넌트 구현

frontend/src/@common/components/Input/Input.style.ts, frontend/src/@common/components/Input/Input.tsx, frontend/src/assets/icons/clock.svg, frontend/src/assets/icons/search.svg
- 프로젝트에서 사용할 공통 Input 컴포넌트 개발
- primary, disabled, error 3가지 variant 제공
- label이 포함된 컴포넌트
기본 형태
|기본|primary에 포커스|error에 포커스|
|---|---|---|
|<img width="698" height="504" alt="image" src="https://github.com/user-attachments/assets/768aef85-3f30-4f67-a0f8-0a3e394871e3" />|<img width="470" height="330" alt="image" src="https://github.com/user-attachments/assets/b2de9099-fdd0-4aac-99e4-a5dc922d1f34" />|<img width="448" height="319" alt="image" src="https://github.com/user-attachments/assets/2319b9bf-5067-4fab-b77f-bc876faedf9e" />|
- 추후 storybook 테스트 필요
- input 내의 icon에 대한 논의 필요
- radius는 figma 상에는 0.675rem 이였는데 0.6rem으로 구현
- type을 time으로 지정하는 경우 스타일 커스텀이 불가함. 논의 필요
close #21
=> feat: Input 컴포넌트 구현

frontend/src/@common/components/Card/Card.styles.ts, frontend/src/@common/components/Card/Card.tsx, frontend/src/@common/components/Input/Input.style.ts, frontend/src/@common/components/Input/Input.tsx, frontend/src/assets/icons/clock.svg, frontend/src/assets/icons/search.svg
- 프로젝트에서 공통으로 사용할 Card 컴포넌트 구현
- default, available, unavailable, disabled 4가지의 variant 제공
- 추후에 스토리북 구현 필요
close #18
=> feat: Card 컴포넌트 구현

frontend/src/@common/components/Modal/Modal.style.ts, frontend/src/@common/components/Modal/Modal.tsx
모달 컴포넌트 구현
추후 모든 도메인 모달 컴포넌트는 해당 컴포넌트를 기반으로 구현한다
- 모달 관련 훅 컨텍스트 혹은 커스텀 훅 분리에 대한 의논 필요
- 외부 스크롤 차단 방식에 대한 검토 필요
close #20
=> feat: Modal 컴포넌트 구현

.github/ISSUE_TEMPLATE/EPIC.md, .github/ISSUE_TEMPLATE/STORY.md, .github/ISSUE_TEMPLATE/TASK.md
이슈 템플릿의 구분선으로 인해 UI 가 좋지 않았음.
구분선을 제거해 가독성을 향상.
=> chore: 이슈 템플릿 구분선 제거

frontend/src/@common/components/Card/Card.styles.ts, frontend/src/@common/components/Card/Card.tsx, frontend/src/@common/components/Card/Card.types.ts, frontend/src/styles/global.css, frontend/src/styles/reset.css
프로젝트에서 공통으로 쓰이는 Card 컴포넌트에 width와 height 속성이 누락되었다는 문제를 발견
closes #89
=> feat: Card 컴포넌트에 width와 height 속성 추가

frontend/src/@common/components/Pill/Pill.style.ts, frontend/src/@common/components/Pill/Pill.tsx, frontend/src/@common/components/Pill/Pill.types.ts
=> feat: Pill 공통 컴포넌트 구현

backend/spring-routie/build.gradle, backend/spring-routie/src/main/java/routie/routiespace/controller/RoutieSpaceController.java, backend/spring-routie/src/main/java/routie/routiespace/controller/dto/request/UpdateRoutieSpaceNameRequest.java, backend/spring-routie/src/main/java/routie/routiespace/controller/dto/response/UpdateRoutieSpaceNameResponse.java, backend/spring-routie/src/main/java/routie/routiespace/domain/RoutieSpace.java, backend/spring-routie/src/main/java/routie/routiespace/exception/RoutieSpaceExceptionHandler.java, backend/spring-routie/src/main/java/routie/routiespace/repository/RoutieSpaceRepository.java, backend/spring-routie/src/main/java/routie/routiespace/service/RoutieSpaceService.java
루티 스페이스의 이름을 변경할 수 없없다.
루티 스페이스의 이름은 변경될 수 있어야 한다.
루티 스페이스 이름 변경 API를 구현한다.
Closes #102
=> feat: 루티 스페이스 이름 수정 API 구현

.github/workflows/backend-dev-ci.yml
CD 스크립트에서 develop 브랜치 push 이벤트에 대해 빌드, 테스트, 배포 전부 수행 중임. 
CI에서 중복 수행중이므로 push 트리거 조건 제거 필요.
```yml
name: CI on develop branch
on:
push:
branches: [ "develop" ]
paths:
- 'backend/**'
pull_request:
branches: [ "develop" ]
types: [opened, synchronize, reopened]
paths:
- 'backend/**'
```
- ci develop 브랜치에서 push 트리거 조건 제거
```yml
name: CI on develop branch
on:
pull_request:
branches: [ "develop" ]
types: [opened, synchronize, reopened]
paths:
- 'backend/**'
```
close #129
=> chore: CI 트리거 조건 수정

frontend/src/@common/components/Header/Header.style.ts, frontend/src/@common/components/Header/Header.tsx, frontend/src/pages/Home/Home.tsx
=> feat: 홈페이지 UI 구현

frontend/src/layouts/Sidebar/Sidebar.tsx, frontend/src/layouts/Sidebar/TimeInput.tsx
- 공통 컴포넌트를 조합해 사이드바 레이아웃 구현
스토리북 대신 실행화면 사진 첨부
close #146
=> feat: 사이드바 레이아웃 구현

frontend/src/layouts/PlaceList/PlaceList.tsx
- 구현된 컴포넌트들을 조합해 장소 목록 레이아웃 구현
스토리북 대신에 실행화면 첨부합니다
close #147
=> feat: 장소 목록 레이아웃 구현

backend/spring-routie/src/main/java/routie/place/controller/dto/response/PlaceReadResponse.java, backend/spring-routie/src/main/java/routie/place/domain/Place.java, backend/spring-routie/src/main/java/routie/place/service/PlaceService.java, backend/spring-routie/src/main/java/routie/routie/controller/dto/request/RoutieUpdateRequest.java, backend/spring-routie/src/main/java/routie/routie/controller/dto/response/RoutieUpdateResponse.java, backend/spring-routie/src/main/java/routie/routie/domain/RoutiePlace.java, backend/spring-routie/src/main/java/routie/routie/service/RoutieService.java, backend/spring-routie/src/main/resources/schema.sql, backend/spring-routie/src/test/java/routie/place/controller/PlaceControllerTest.java
Reverts woowacourse-teams/2025-routie#156
=> Revert "fix: 엔티티 컬럼 위치 수정"

backend/spring-routie/src/main/java/routie/auth/config/WebMvcConfig.java
- 브라우저의 preflight 요청 시 cors 응답 필요
- cors 설정 추가
- dev 환경에서는 모든 경로에 대해 허용
close #160
=> chore: dev 환경에서만 동작하는 cors 설정 추가

backend/spring-routie/src/main/java/routie/auth/config/WebMvcConfig.java
프론트엔드에서 응답의 Location 헤더를 읽을 수 없는 문제 발생
cors에서 응답의 Location 헤더를 읽을 수 있는 권한 추가
=> chore: 프론트엔드에서 응답의 Location 헤더를 읽을 수 있는 권한 추가

frontend/src/domains/places/components/EditPlaceModal/EditPlaceModal.tsx, frontend/src/domains/places/components/EditPlaceModal/EditPlaceModalButtons.tsx, frontend/src/domains/places/components/EditPlaceModal/EditPlaceModalHeader.tsx, frontend/src/domains/places/components/PlaceFormSection/PlaceForm.types.ts, frontend/src/domains/places/components/PlaceFormSection/RequiredInfoSection.tsx, frontend/src/domains/places/hooks/useAddPlaceForm.ts
- 장소 정보 수정을 할 모달 컴포넌트가 필요
- 장소 정보 수정 모달 컴포넌트 구현
스토리북 대신 실행화면 첨부
- 해당 모달에서는 하단의 닫기버튼을 제거하였습니다.
- TODO 주석이 달린 부분의 변수가 사용되지 않아서 린트 에러가 발생하고 있는데 실행에는 문제 없습니다.
- 필수 정보 입력 Input들은 기획대로 disable 처리하였습니다.
close #104
=> feat: 장소 정보 수정 모달 컴포넌트 구현

frontend/src/layouts/Sidebar/Sidebar.tsx, frontend/src/pages/RoutieSpace/RoutieSpace.tsx
- 사이드 바, 장소 목록 레이아웃을 조합하여 루티 스페이스 페이지 구현
실행화면
close #175
=> feat: 루티 스페이스 페이지 구현

frontend/src/apis/index.ts, frontend/src/domains/routieSpace/apis/routieSpaceName.ts, frontend/src/domains/routieSpace/components/RoutieSpaceName/RoutieSpaceName.tsx
- 루티 스페이스 이름 조회
- 루티 스페이스 이름 수정
Closes #188
=> feat: 루티 스페이스 이름 조회 및 수정 api 연결

backend/spring-routie/src/main/java/routie/routie/domain/Routie.java, backend/spring-routie/src/main/java/routie/routiespace/domain/RoutieSpace.java
기본 루티가 존재하지 않았음
기본 루티가 생성되도록 변경
Closes #192
=> feat: 루티 스페이스 생성 시 루티 하나가 함께 추가되도록 구현

backend/spring-routie/src/main/java/routie/routiespace/controller/RoutieSpaceController.java, backend/spring-routie/src/main/java/routie/routiespace/controller/dto/response/RoutiesResponse.java, backend/spring-routie/src/main/java/routie/routiespace/service/RoutieSpaceService.java
루티 스페이스의 정보를 조회할 수 없었다
루티 스페이스의 정보를 조회할 수 있도록 API 를 추가한다
Closes #191
=> feat: 루티 스페이스의 전체 루티 조회 API 구현

frontend/src/domains/routie/components/RoutieValidationResultCard/RoutieValidationResultCard.tsx, frontend/src/layouts/Sidebar/Sidebar.tsx, frontend/src/layouts/Sidebar/TimeInput.tsx
토글 상태에 따른 UI 구현
https://github.com/user-attachments/assets/be397e57-69b8-456c-8e02-5036b3f3ea72
Closes #195
=> feat: 토글 상태에 따른 UI 구현

frontend/src/domains/places/apis/addPlace.ts, frontend/src/domains/places/components/AddPlaceModal/AddPlaceModal.tsx
- 장소 추가 모달의 submit 버튼을 누르면 서버에 장소를 추가할 수 있게 api 연결하였습니다.
인증합니다.
close #193
=> feat: 장소 추가 모달과 장소 추가 api 연결

frontend/src/domains/places/apis/getPlace.ts, frontend/src/domains/places/components/EditPlaceModal/EditPlaceModal.tsx, frontend/src/domains/places/components/PlaceCard/PlaceCard.tsx
- 장소 수정을 위해 선택된 장소의 데이터를 조회하는 api 연결
- 장소 수정 버튼을 누르면 조회된 장소 정보들이 모달의 폼을 채움
인증합니다
close #201
=> feat: 장소 수정을 위해 선택된 장소의 데이터를 조회하는 api 연결

backend/spring-routie/src/main/java/routie/docs/config/SwaggerConfig.java, backend/spring-routie/src/main/java/routie/place/domain/PlaceClosedWeekday.java, backend/spring-routie/src/main/java/routie/routiespace/domain/RoutieSpace.java
- 휴무일 `MONDAY,SUNDAY` -> `TUESDAY`와 같이 완전히 바뀌어야 200, `MONDAY,SUNDAY` -> `TUESDAY,SUNDAY`와 같이 하나라도 겹치면 에러 발생하는 문제
- 제약조건을 제거해 문제 해결
=> hotfix: 장소 수정 시 특정 경우에 에러 발생하는 문제 해결

frontend/src/domains/places/apis/editPlace.ts, frontend/src/domains/places/components/EditPlaceModal/EditPlaceModal.tsx, frontend/src/domains/places/components/PlaceCard/PlaceCard.tsx, frontend/src/layouts/PlaceList/PlaceList.tsx
- 장소 수정 모달에 장소 수정 api 연결
- 수정이 성공하면 장소 목록을 refetch하여 최신 데이터를 받아오도록 하였습니다.
close #202
=> feat: 장소 수정 모달에 장소 수정 api 연결

frontend/.eslintrc.cjs, frontend/package.json, frontend/src/__test__/pass.test.ts, frontend/tsconfig.json, frontend/vitest.config.ts
ci 환경을 세팅하기 위해 ESLint 규칙이 에러로 뜨는 것을 경고로 변경하고, Vitest 설정을 추가한다. 
close #218
=> chore: ESLint 규칙 경고로 변경 및 Vitest 설정 추가

frontend/package.json, frontend/tsconfig.json, frontend/vitest.config.mts
=> chore: 프로젝트 설정 파일 수정

frontend/src/domains/places/components/AddPlaceModal/AddPlaceModal.tsx, frontend/src/layouts/PlaceList/PlaceList.tsx, frontend/src/layouts/Sidebar/Sidebar.tsx, frontend/src/pages/RoutieSpace/RoutieSpace.tsx
- 장소를 추가했을 때 장소 목록에 바로 반영이 안되는 문제 발견
- 장소를 추가했을 때 장소 목록도 바로 업데이트 되도록 함
- 이 기능을 위해 RoutieSpace page에 placeList 상태 끌어올리기를 함
close #212
=> feat: 장소 추가시 장소 목록을 업데이트 하기 위한 상태 끌어올리기

backend/spring-routie/src/main/java/routie/routie/service/RoutieService.java
=> hotfix: 루티 수정 호출 시 기존 루티 플레이스들을 삭제

backend/spring-routie/src/main/java/routie/place/infrastructure/traveltimecalculator/FakeDrivingTravelTimeCalculator.java
장소 간 이동 시간 Mock 데이터가 6000(분)으로 설정되어있었음.
이동 시간이 너무 길어 테스트에 어려움이 있음.
장소 간 이동 시간 Mock 데이터를 10(분)으로 변경
Closes #229
=> refactor: 장소 간 이동 거리 계산 Mock 데이터 변경

frontend/src/domains/places/components/PlaceCard/PlaceCard.tsx, frontend/src/domains/routie/apis/routie.ts, frontend/src/domains/routie/components/RoutieValidationUnavailableCard/RoutieValidationUnavailableCard.tsx, frontend/src/layouts/PlaceList/PlaceList.tsx, frontend/src/layouts/Sidebar/Sidebar.tsx, frontend/src/pages/RoutieSpace/RoutieSpace.tsx
장소 선택 버튼에 api를 연동해 루티 목록에 추가 및 삭제를 구현
https://github.com/user-attachments/assets/a58d056e-b39c-4caa-b5eb-30f5b3143d6c
=> feat: 장소 선택 기능 api 연동

backend/spring-routie/src/main/java/routie/routie/infrastructure/routievaliditycalculator/BreaktimeValidityCalculator.java, backend/spring-routie/src/main/java/routie/routie/service/RoutieService.java
- 반환 값이 잘못된 계산 식을 통해 도출
- 브레이크타임의 시작 시각과 방문 종료 시각이 일치하는 경우 false를 반환하는 문제
- 잘못된 계산 식 정정
- 검증식이 엣지케이스를 포함하도록 수정
Closes #237
=> refactor: 동선 검증 로직 개선

frontend/src/layouts/Sidebar/Sidebar.tsx
```ts
if (isSequenceChanged) {
const sortedPlaces = updated.sort((a, b) => a.sequence - b.sequence);
setRoutiePlaces(sortedPlaces);
editRoutieSequence(sortedPlaces);
validateRoutie();
}
```
```ts
const updateRoutiePlaces = async (sortedPlaces: Routie[]) => {
setRoutiePlaces(sortedPlaces);
await editRoutieSequence(sortedPlaces);
await validateRoutie();
};
if (isSequenceChanged) {
const sortedPlaces = updated.sort((a, b) => a.sequence - b.sequence);
updateRoutiePlaces(sortedPlaces);
}
```
=> refactor: sidebar 내부 비동기 처리가 필요한 로직에 누락된 await 적용

backend/spring-routie/src/main/java/routie/routie/controller/RoutieController.java, backend/spring-routie/src/main/java/routie/routie/controller/dto/request/RoutiePlaceCreateRequest.java, backend/spring-routie/src/main/java/routie/routie/controller/dto/response/RoutiePlaceCreateResponse.java, backend/spring-routie/src/main/java/routie/routie/domain/Routie.java, backend/spring-routie/src/main/java/routie/routie/service/RoutieService.java, backend/spring-routie/src/test/java/routie/routie/controller/RoutieControllerTest.java
루티에 장소를 "추가"할 수 있는 기능이 존재하지 않았음.
루티에 장소를 추가할 수 있는 api 구현
Closes #291
=> feat: 루티 장소 추가 api 구현

backend/spring-routie/src/main/java/routie/routie/domain/Routie.java
루티 테이블 제거에 따른 루티 장소 테이블 컬럼명 변경
routie_places 테이블의 routie_id 컬럼명을 routie_space_id로 변경
Closes #308
=> refactor: 루티 테이블 제거에 따른 루티 장소 테이블 컬럼명 변경

backend/spring-routie/src/main/java/routie/routie/controller/RoutieController.java, backend/spring-routie/src/main/java/routie/routie/domain/Routie.java, backend/spring-routie/src/main/java/routie/routie/domain/RoutiePlace.java, backend/spring-routie/src/main/java/routie/routie/service/RoutieService.java, backend/spring-routie/src/main/java/routie/routiespace/domain/RoutieSpace.java, backend/spring-routie/src/test/java/routie/routie/controller/RoutieControllerTest.java, backend/spring-routie/src/test/java/routie/routiespace/domain/RoutieSpaceFixture.java
루티에 장소를 "삭제"할 수 있는 기능이 존재하지 않았음.
루티에 장소를 삭제할 수 있는 api 구현
Closes #313
=> feat: 루티 장소 삭제 api 구현

frontend/src/domains/routie/hooks/useRoutieValidate.ts, frontend/src/layouts/PlaceList/PlaceList.tsx, frontend/src/layouts/Sidebar/Sidebar.tsx
- 루티에 장소가 없어도 검증 요청을 보내는 문제를 발견
- 루티에 장소가 없는 경우 검증 요청을 보내지 않게 수정
https://github.com/user-attachments/assets/ddd3f673-4e13-4c40-8cfa-b04df445130c
검증 기능이 활성화 되어 있지만 루티에 장소가 없는 경우 안내 카드에 다른 메시지를 보여주는게 좋을거 같은데 의견 부탁드립니다 🤔
Closes #314
=> refactor: 검증 요청 시점 제한 추가

frontend/src/domains/routie/components/EmptyRoutieMessage/EmptyRoutieMessage.tsx, frontend/src/layouts/Sidebar/Sidebar.tsx
장소가 동선에 추가되지 않아, 동선이 비어있는 상태인 경우에 화면에 안내 문구를 표시한다. 
https://github.com/user-attachments/assets/a2e33b6b-4911-4422-80b3-34ff0459d2f0
close #341
=> feat: 빈 동선 메시지 컴포넌트 추가 및 사이드바에 통합

backend/spring-routie/src/main/java/routie/routie/controller/RoutieController.java, backend/spring-routie/src/main/java/routie/routie/controller/dto/response/RoutieReadResponse.java, backend/spring-routie/src/main/java/routie/routie/controller/dto/response/RoutieValidationResponse.java, backend/spring-routie/src/main/java/routie/routie/domain/route/RouteCalculator.java, backend/spring-routie/src/main/java/routie/routie/domain/route/Routes.java, backend/spring-routie/src/main/java/routie/routie/domain/routievalidator/RoutieValidator.java, backend/spring-routie/src/main/java/routie/routie/domain/routievalidator/ValidationResult.java, backend/spring-routie/src/main/java/routie/routie/domain/routievalidator/ValidationStrategy.java, backend/spring-routie/src/main/java/routie/routie/domain/timeperiod/TimePeriodCalculator.java, backend/spring-routie/src/main/java/routie/routie/domain/timeperiod/TimePeriods.java, backend/spring-routie/src/main/java/routie/routie/infrastructure/routievalidator/BreaktimeValidator.java, backend/spring-routie/src/main/java/routie/routie/infrastructure/routievalidator/ClosedDayValidator.java, backend/spring-routie/src/main/java/routie/routie/infrastructure/routievalidator/OperationHoursValidator.java, backend/spring-routie/src/main/java/routie/routie/infrastructure/routievalidator/RoutieValidatorComposite.java, backend/spring-routie/src/main/java/routie/routie/infrastructure/routievalidator/TotalTimeValidator.java, backend/spring-routie/src/main/java/routie/routie/service/RoutieService.java, backend/spring-routie/src/test/java/routie/routie/controller/RoutieControllerTest.java, backend/spring-routie/src/test/java/routie/routie/infrastructure/routievalidator/BreaktimeValidatorTest.java, backend/spring-routie/src/test/java/routie/routie/infrastructure/routievalidator/ClosedDayValidatorTest.java, backend/spring-routie/src/test/java/routie/routie/infrastructure/routievalidator/OperationHoursValidatorTest.java, backend/spring-routie/src/test/java/routie/routie/service/RoutieServiceValidationTest.java
- 검증 기능을 통해 가능 여부만 응답했음
- Routes와 TimePeriods 일급 컬렉션이 불변 값을 반환하도록 보완
- API Endpoint를 `GET /validity` 에서 `POST /validate` 로 수정 (검증 행위를 더 잘 드러내도록)(+ 추후 request body가 필요할 것 같다는 짐작)
- 검증 API의 응답값 변경
- 변경 사항에 따라 Test도 수정
```
{
"isValid": true,
}
```
```
{
"validationResultResponses": [
{
"strategy": "루티 전체 시간 초과 여부",
"code": "IS_WITHIN_TOTAL_TIME",
"isValid": true,
"invalidRoutiePlaces": [
]
},
{
"strategy": "휴무일 방문 여부",
"code": "IS_NOT_CLOSED_DAY",
"isValid": false,
"invalidRoutiePlaces": [
{
"routiePlaceId":1
}    
]
},
{
"strategy": "운영 시간 내 방문 여부",
"code": "IS_WITHIN_OPERATION_HOURS",
"isValid": true,
"invalidRoutiePlaces": [
]
},
{
"strategy": "브레이크 타임 방문 여부",
"code": "IS_NOT_DURING_BREAKTIME",
"isValid": true,
"invalidRoutiePlaces": [
]
}
]
}
```
=> refactor: 루티 검증 기능 API 수정

backend/spring-routie/.gitignore, backend/spring-routie/build.gradle, backend/spring-routie/src/main/resources/application.yml, backend/spring-routie/src/main/resources/logback-dev.xml, backend/spring-routie/src/main/resources/logback-spring.xml
로그를 기록하고 모니터링하고 있지 않음
- logback 설정 추가
- error 로그 
- 저장 경로: `logs/routie-error.json`
- 출력 형식: JSON
- 유지 기간: 7일
- info, warn 로그
- 저장 경로: `logs/routie-info.log`
- 출력 형식: raw String (디폴트 콘솔 출력과 동일)
- 유지 기간: 7일
=> chore: Logback을 이용한 error, warn, info 로깅 설정 추가

backend/spring-routie/build.gradle, backend/spring-routie/src/main/resources/logback-dev.xml, backend/spring-routie/src/main/resources/logback-spring.xml
- 콘솔에 debug 레벨의 로그도 출력되고 있어 혼란스러움
- logback 설정이 local 환경에서도 동작하고 있음
- info 레벨 이상의 로그만 콘솔에 출력되도록 수정
- dev 환경에서만 로거가 동작하도록 수정
---
- 겸사겸사 build.gradle에서 swagger 의존성 표현 방식 수정
=> chore: Logback 설정 수정

frontend/package-lock.json, frontend/package.json, frontend/src/domains/places/components/PlaceCard/PlaceCard.tsx, frontend/src/domains/routie/components/RoutiePlaceCard/RoutiePlaceCard.tsx, frontend/src/layouts/Sidebar/Sidebar.tsx, frontend/src/libs/googleAnalytics/hooks/useGoogleAnalytics.ts, frontend/src/libs/googleAnalytics/hooks/useGoogleEventTrigger.ts, frontend/src/routes/index.tsx
Google Analytics로 사용자 행동 모니터링 환경 구축
이벤트 트래킹 훅 구현 결과
Closes #362
=> chore: ga 설정

frontend/src/layouts/Sidebar/Sidebar.tsx
병합 과정에서 일정 입력 input이 중복으로 생김
중복된 일정 입력 input 제거
Closes #389
=> fix: 병합 과정에서 중복된 일정 입력 input 제거

frontend/package-lock.json, frontend/package.json, frontend/src/index.tsx
에러 트래킹 환경 구축을 위해 sentry의 초기 세팅을 진행하였습니다. 
close #377
=> chore: sentry 초기 세팅

.github/workflows/backend-dev-cd.yml, .github/workflows/backend-prod-cd.yml, .github/workflows/backend-prod-ci.yml
프로덕션 환경의 자동화가 필요함.
프로덕션 git workflow 작성
=> chore: 백엔드 프로덕션 git workflow 작성

.github/workflows/backend-prod-cd.yml, .github/workflows/backend-prod-ci.yml
workflow 이름이 develop branch라고 표기
workflow 이름을 main branch로 정정
=> chore: git workflow 이름 정정

backend/spring-routie/src/main/java/routie/logging/aspect/RequestLoggingAspect.java, backend/spring-routie/src/main/java/routie/logging/config/DevLoggingConfig.java, backend/spring-routie/src/main/java/routie/logging/config/ProdLoggingConfig.java, backend/spring-routie/src/main/java/routie/logging/extractor/ClientIpExtractor.java, backend/spring-routie/src/main/java/routie/logging/interceptor/RequestLoggingInterceptor.java, backend/spring-routie/src/main/java/routie/logging/logger/ClientRequestLogger.java, backend/spring-routie/src/main/resources/logback-prod.xml, backend/spring-routie/src/main/resources/logback-spring.xml
- prod 환경에서 로그를 파일로 저장하지 않음
- 지정된 경로에 `routie-request.json`이라는 이름으로 로그를 저장
- prod 환경 로그 기록 필드
- timestamp
- level
- traceId
- responseTimeMs
- httpMethod
- url
- clientIp
**예시**
```json
{
"timestamp": "2025-08-07T11:22:31.532+09:00",
"level": "INFO",
"traceId": "219cd3c1-f3f5-40f5-9cd3-c1f3f5b0f57c",
"responseTimeMs": "191",
"httpMethod": "GET",
"url": "/routie-spaces/ut-1/places",
"clientIp": "127.0.0.1"
}
```
=> feat: prod 환경 로그 기록 구현

.github/workflows/backend-dev-cd.yml, .github/workflows/backend-prod-cd.yml
echo 명령어로 application.yml을 출력할 때 플레이스홀더 값이 환경 변수로 치환되면 안되는데, 치환되고 있음.
echo 시 큰따옴표를 사용하면 환경 변수 값이 치환되어 출력되고, 작은따옴표를 사용하면 문자 그대로 출력됨. 
치환이 안된 상태로 출력하기 위해 큰따옴표를 작은 따옴표로 수정.
close #415
=> chore: cd 워크플로우 파일에서 echo 출력 방식 수정

backend/spring-routie/src/main/java/routie/auth/config/DevCorsConfig.java, backend/spring-routie/src/main/java/routie/auth/config/ProdCorsConfig.java
프로덕션 환경에서 cors 문제 발생.
프로덕션 환경 cors 설정 추가.
=> feat: 프로덕션 환경 cors 설정 추가

backend/spring-routie/src/main/java/routie/routie/infrastructure/routecalculator/driving/kakaodrivingapi/KakaoDrivingRouteApiClientConfig.java, backend/spring-routie/src/main/java/routie/routie/infrastructure/routecalculator/driving/kakaodrivingapi/KakaoDrivingRouteApiRequest.java
자동차 이동 시 장소 간 이동 거리와 시간 계산에서 Mock 위/경도를 사용중이었음.
이로 인해 신뢰도가 떨어짐.
Mock 데이터 대신 실제 데이터를 사용하도록 변경.
Closes #409
=> feat: 자동차 이동 시 장소 간 이동 거리, 시간 계산에서 실제 데이터를 사용하도록 변경

backend/spring-routie/src/main/java/routie/routie/infrastructure/routecalculator/driving/DrivingRouteCalculator.java
자동차 이동 시간 계산 시, 응답이 초단위였음.
분단위로 응답하도록 변경.
=> refactor: 자동차 이동 시간 계산 시, 응답을 분단위로 하도록 변경

.github/workflows/frontend-dev-ci.yml, frontend/.eslintrc.cjs, frontend/.gitignore, frontend/package-lock.json, frontend/package.json, frontend/webpack.common.js, frontend/webpack.dev.js, frontend/webpack.prod.js
개발을 마친 뒤, 실제 배포 전과 같은 조건에서 동작을 검증하기위한 환경 분리가 필요했음
프로덕션, 개발 환경 분리를 위한 웹팩 세팅을 했습니다.
센트리 관련 오류 무조건 해결해야 함
```
Invalid Sentry Dsn: 'https://399b3634cc3cf18a4b63d766...
```
=> chore: 프로덕션, 개발 환경 분리를 위한 웹팩 세팅

backend/spring-routie/src/main/java/routie/place/domain/Place.java
PR #484 에서 로컬에서 git push 후, 웹에서 바로 merge를 눌렀는데 마지막에 push 되지 않은 2개의 커밋이 반영되지 않음
- nullable = true 제거
- roadAddressName 검증 로직 indent 감소
closes #490
=> refactor: Place 엔티티 소규모 리팩링

.github/workflows/setup-open-pr.yml
커밋 타입 -> PR 라벨
feat -> feat
feat -> feature
closes #491
=> chore: feat 커밋 타입에 해당하는 PR 라벨명 수정

frontend/src/@common/components/Toast/Toast.styles.ts, frontend/src/@common/components/Toast/Toast.tsx, frontend/src/@common/contexts/useToastContext.tsx, frontend/src/@common/hooks/useToast.ts, frontend/src/@common/types/toast.type.ts, frontend/src/routes/index.tsx
에러 메시지 & 특정 동작의 수행이 완료되었는지 알려줄 수 있는 적절한 UI가 없었음
- 토스트 컴포넌트 구현
- 토스트 컨텍스트 구현
https://github.com/user-attachments/assets/77254dc0-9e0d-4174-8dcf-4887783d47e4
디자인 & 컬러 관련해서 의견 많이 주시면 좋을거 같습니다~
Closes #453
=> feat: toast 기능 구현

backend/spring-routie/src/main/java/routie/place/domain/SearchedPlace.java
`SearchedPlace` 클래스에서 도로명 주소가 null일 경우 예외를 던지고 있음. 
저번 지번 주소 추가 수정 PR에서 수정이 덜 됨.
도로명 주소는 nullable, 지번 주소는 필수로 수정
closes #507 #507
=> fix: 도로명 주소는 null일 수 있고, 지번 주소는 null일 수 없도록 수정

backend/spring-routie/src/main/java/routie/place/controller/dto/response/PlaceListResponse.java
- 클라이언트 측에 장소 카드에 브레이크 타임 필요
- 응답 추가
closes #526
=> feat: 응답 필드에 브레이크 타임 추가

frontend/src/domains/maps/hooks/useMapMarker.ts
배포 환경에서 발생하는 문제라 바로 배포 하고 확인하겠습니다
Closes #528
=> fix: 카카오 지도가 마커의 장소 위치로 이상하게 이동하는 문제 수정

frontend/src/domains/maps/components/KakaoMap.tsx, frontend/src/domains/maps/hooks/useCustomOverlay.ts, frontend/src/domains/maps/hooks/useMapMarker.ts
- 초기 장소를 대한민국 전체를 보여줄 때 카카오 맵의 절대 사이즈 때문에 큰 화면에서 잘리는 문제를 발견
- 첫 장소를 추가할 때 panTo가 정확한 위치를 찾지 못하는 문제를 발견
- 지도 초기화가 완료되기 전에 마커, 동선 등록이 실행되는 문제 발견
- 초기 장소를 서울로 고정 (장소가 없을 때)
- 장소를 추가할 때는 setBounds를 실행하게 수정
- 지도 초기화, 이벤트 등록, 마커 등록, 동선 등록이 순차적으로 실행되기 수정
=> fix: 수정 이후에도 제대로 지도가 동작하지 않는 문제 수정

frontend/src/domains/maps/components/KakaoMap.tsx, frontend/src/domains/maps/hooks/useMapMarker.ts
- 마커에 호버했을 때 장소 이름 툴팁이 뜰 수 있게 추가
Closes #544
=> feat: marker title 추가

frontend/src/domains/maps/components/KakaoMap.tsx, frontend/src/domains/maps/hooks/useKakaoMapInit.ts, frontend/src/domains/maps/types/KaKaoMap.types.ts
- 지도가 무한으로 축소되어 지도가 아닌 영역이 보이는 문제를 발견
- 최대 축소 레벨 제한을 추가해 최대한 이런 문제를 방지한다
Closes #537
=> feat: 지도 최대 zoom level 제한 추가

frontend/src/domains/places/components/SearchAddress/SearchAddress.tsx, frontend/src/domains/places/components/SearchBox/SearchBox.tsx, frontend/src/domains/places/components/SearchList/SearchEmptyList.tsx, frontend/src/domains/places/components/SearchList/SearchEmptyState.tsx, frontend/src/domains/places/components/SearchList/SearchList.styles.ts, frontend/src/domains/places/components/SearchList/SearchList.tsx, frontend/src/domains/places/hooks/useSearchPlace.ts
- 장소 검색 결과가 없으면, 아무런 안내와 창이 뜨지 않음
- 도로명 주소가 없다면 아무런 내용을 보여지 않음
- 장소 검색 결과가 없으면 '{키워드}에 대한 검색 결과가 없습니다.' 나오도록 구현
- 도로명 주소가 없다면, 지번 주소를 보여주도록 구현
https://github.com/user-attachments/assets/6416ee8d-5548-4b90-9acf-89a66c921de4
Closes #505
=> feat: 검색한 장소에 대해 결과가 있다면 도로명 또는 지번 사용하도록 구현

frontend/.eslintignore, frontend/package-lock.json, frontend/package.json, frontend/public/mockServiceWorker.js, frontend/src/index.tsx, frontend/src/mocks/browser.ts, frontend/src/mocks/handlers.ts, frontend/src/mocks/node.ts, frontend/webpack.dev.js
- api 병합이 늦어지면 프론트엔드 개발에 병목이 생기는 문제 발견
- msw 세팅
Closes #432
=> chore: msw 초기 세팅

frontend/src/domains/routie/components/SelectMovingStrategy/SelectMovingStrategy.tsx, frontend/src/domains/routie/contexts/useRoutieContext.tsx, frontend/src/domains/routie/hooks/useMovingStrategy.ts
- 이동 수단 관리 훅 구현
- 추후에 루티 조회, 루티 검증 요청에 이동 수단 정보가 필요해 RoutieContext에서 훅을 호출
- 새로고침해도 선택한 이동 수단 정보가 초기화되지 않게 세션 스토리지에 저장
실수로 브랜치에 이슈 번호를 잘못 입력했습니다... 다음부터 조심하겠습니다 🥲
Closes #538
=> feat: useMovingStrategy 훅 구현

frontend/src/domains/maps/components/KakaoMap.tsx
=> refactor: 동선만 보기 기능 제거

frontend/src/domains/routie/components/RoutiePlaceCard/RoutiePlaceCard.tsx
isUnavailable가 제대로 계산 안되는 오류 수정
=> fix: routie.id를 이용하여 isUnavailable를 구하도록 수정

frontend/src/domains/places/components/PlaceCard/PlaceCard.tsx
장소 카드에서 브레이크를 브레이크 타임으로 수정
추후에 디자인 바뀔 것을 고려하여 기교부리지 않고 하드코딩하였습니다. 😊
추가로, 브레이크 타임이 없는 경우 영업시간과 그에 대한 시각이 너무 떨어져있는 것처럼 보이는데 왔다갔다하는 것보다 위치를 고정해주는 게 더 나을 것 같다는 생각을 하였습니다! 의견 있으시다면 코멘트 주세용 🙇‍♀️
Closes #622
=> refactor: 장소 카드 브레이크 -> 브레이크 타임으로 수정

frontend/src/domains/maps/hooks/useKakaoMapInit.ts
지도의 zoom level 제한이 설정되어있어서 동선이 한 눈에 보이지 않는 문제 발견
zoom level을 제한하는 코드 제거
Closes #631
=> refactor: 지도 zoom level limit 제거하도록 수정

frontend/src/domains/routie/apis/routie.ts, frontend/src/domains/routie/contexts/useRoutieContext.tsx
- 루티 장소에 동선 검증을 하지 않을 때, 출발 시간 및 도착 시간이 안 보이는 문제
- 동선 검증과 상관 없이 출발 시간 및 도착 시간이 보이도록 수정
https://github.com/user-attachments/assets/f95fbe33-fee7-4193-b4b7-e6b93b7f693d
Closes #641
=> fix: 루티 장소에 검증을 하지 않을 때도 출발 시간, 도착 시간이 보이도록 수정

frontend/src/domains/routie/components/RoutieValidationWaitingCard/RoutieValidationWaitingCard.tsx, frontend/src/domains/routie/hooks/useRoutieTime.ts, frontend/src/domains/routie/hooks/useRoutieValidate.ts, frontend/src/domains/routie/types/routie.types.ts
- useRoutieTime 훅 분리
- 시작, 종료 시간에 기본 값 추가
- 시간에 대한 예외 처리 (시작 < 종료 막기), 키보드 입력 막기 등은 이후에 추가하겠습니다
Closes #628
=> refactor: routieTime 기본 값 추가

frontend/public/index.html
머리채 계정에서 발급받은 kakao app key로 변경하였습니다. 
지도 잘 뜹니다!
.env 파일에 app key를 넣어야하나 고민했었는데, kakao developers에서 웹 플랫폼을 local, dev, prod로 등록해놓았고, 등록된 도메인 이외에서는 사용할 수 없는 것으로 확인이 되어, 노출시켜도 될 것 같아 따로 분리하지 않고 index.html에 넣었습니다. 🫡
Closes #649
=> refactor: kakao app key로 변경

.github/workflows/backend-dev-cd.yml, .github/workflows/backend-prod-cd.yml, backend/spring-routie/build.gradle, backend/spring-routie/src/main/resources/application.yml, backend/spring-routie/src/main/resources/db/migration/V1__init.sql
- DB 마이그레이션이 어려웠음
- Flyway 설정 추가
- Local 환경: 변경된 application.yml과 추가된 gradle dependency에 따라 Runtime으로 mirgration 실행
- Prod/Dev 환경: gradle plugins에 추가된 의존성에 따라 Gradle Task flywayMigrate를 workflow CD 파일에서 실행, application.yml에서는 Runtime 실행 비활성화
- prod/dev application.yml 수정됨
Closes #654
=> feat: Flyway 설정

frontend/src/layouts/Sidebar/TimeInput.tsx
- 동선 검증이 비활성화 되어서 input의 variant는 disabled인데 실제로는 수정이 가능했음
- isValidateActive를 확인하지 않고 이전 순서의 값이 있는지만 확인했음
- 시작(날짜를 입력했는지) -> 종료 (날짜, 시작 시간을 입력했는지)
기존 조건문에 isValidateActive 값을 추가함
실제 disabled가 적용되면 time picker가 보이지 않습니다!
Closes #656
=> fix: timeInput disabled condition 수정

frontend/src/@common/components/Header/Header.tsx, frontend/src/@common/components/Header/HomeButton/HomeButton.tsx, frontend/src/@common/components/Text/Text.style.ts, frontend/src/@common/components/Text/Text.types.ts, frontend/src/domains/routieSpace/components/RoutieSpaceName/RoutieSpaceName.style.ts, frontend/src/domains/routieSpace/components/RoutieSpaceName/RoutieSpaceName.tsx, frontend/src/layouts/Sidebar/Sidebar.styles.ts, frontend/src/layouts/Sidebar/Sidebar.tsx, frontend/src/layouts/Sidebar/SidebarWhenHowSection.tsx, frontend/src/layouts/Sidebar/SidebarWhereSection.tsx, frontend/src/styles/theme.ts
- 루티 영역이 너무 좁아서 작은 모니터로 보는 경우 루티 카드가 하나만 보이는 문제 발견
- UI 개편
- 디자인 개편
- 스타일 파일 분리
- 섹션별 컴포넌트 분리
Closes #666
=> refactor: Sidebar UI & Design 수정

backend/spring-routie/src/test/java/routie/routie/domain/RoutiePlaceBuilder.java
- RoutiePlaceBuilder 필드 주입 메서드에 파라미터 부재
- RoutiePlaceBuilder 필드 주입 메서드에 알맞은 파라미터 추가
관련 이슈: #437
=> fix: RoutiePlaceBuilder 필드 주입 메서드에 알맞은 파라미터 추가

backend/spring-routie/src/main/java/routie/routie/domain/route/RouteCalculationContext.java, backend/spring-routie/src/main/java/routie/routie/infrastructure/routecalculator/driving/DrivingRouteCalculator.java, backend/spring-routie/src/main/java/routie/routie/infrastructure/routecalculator/transit/TransitRouteCalculator.java
- Route 계산 전 정렬이 안돼 시간 계산 시 문제 발생
- 계산 전 정렬으로 문제 해결
#681
=> fix: 루트 계산 로직 수정

frontend/public/index.html
잘 못된 머지로 인해 카카오맵 키가 변경
fix: 잘 못된 머지로 인해 카카오맵 키가 변경되어 복구
Closes #693
=> fix: 잘 못된 머지로 인해 카카오맵 키가 변경되어 복구

frontend/package-lock.json
package-lock.json 버전을 1.0.0으로 업그레이드
Closes #702
=> chore: package-lock.json 버전 업

.github/workflows/backend-dev-cd.yml, .github/workflows/backend-prod-cd.yml
=> fix: 워크플로우에 포함된 쉘 명령어 오타 수정

backend/spring-routie/src/main/java/routie/business/user/ui/UserController.java, backend/spring-routie/src/main/java/routie/business/user/ui/dto/response/UserInformationResponse.java, backend/spring-routie/src/main/java/routie/business/user/ui/v1/UserControllerV1.java
사용자 정보를 조회할 수단이 존재하지 않았음.
사용자 정보 조회 API 구현을 통해 해소.
Closes #795
=> feat: 사용자 정보 조회 API 구현

backend/spring-routie/src/main/java/routie/business/routiespace/application/RoutieSpaceService.java, backend/spring-routie/src/main/java/routie/business/routiespace/ui/v2/RoutieSpaceControllerV2.java, backend/spring-routie/src/main/java/routie/global/exception/domain/ErrorCode.java
=> feat: 루티스페이스 추가/수정 로그인 권한 로직 적용

frontend/src/domains/places/apis/place.ts, frontend/src/domains/routie/apis/routie.ts, frontend/src/domains/routieSpace/apis/routieSpace.ts
- API 함수 URL 주소가 맞지 않아 최신화 진행
- 장소추가, 삭제, 루티 스페이스 생성, 루티 스페이스 이름 수정, 루티 수정, 루티 장소 삭제 기능 정상 동작 확인했습니다.
Closes #847
=> refactor: API 명세와 실제 API 함수 맞게 최신화
