.github/workflows/discord-notification.yml

- [opened, reopened, synchronized] -> [opened, reopened, labeled]
기존 트리거 기준: [opened, reopened, synchronized]
PR 생성 후 라벨을 부여했을 때 디스코드에 알림이 오지 않음
변경 후 트리거 기준: [opened, reopened, labeled]
PR 생성 후 라벨을 붙여도 디스코드에 알림이 오도록 수정
단, 라벨을 붙였다 뗐다 하면 붙일 때마다 알림 발생함

fix: Discord PR 알람 기능 트리거 기준 수정

---

backend/spring-routie/src/main/java/routie/place/repository/PlaceClosedWeekdayRepository.java
backend/spring-routie/src/main/java/routie/place/repository/PlaceRepository.java
backend/spring-routie/src/main/java/routie/routie/repository/RoutiePlaceRepository.java
backend/spring-routie/src/main/java/routie/routie/repository/RoutieRepository.java
backend/spring-routie/src/main/java/routie/routiespace/repository/RoutieSpaceRepository.java

- 도메인 엔티티들(Place, RoutieSpace, Routie, RoutePlace, PlaceClosedWeekday)에 대한 데이터 접근 계층이 구현되지 않음
- 비즈니스 로직에서 데이터베이스와 상호작용할 수 있는 Repository 인터페이스가 없음
- JPA를 활용한 CRUD 작업 및 커스텀 쿼리 실행이 불가능한 상태
- 각 도메인 엔티티별로 JpaRepository를 상속받는 Repository 인터페이스 생성
closes #105

feat: 엔티티 별 레포지토리 생성

---

.github/workflows/backend-dev-cd.yml
backend/spring-routie/build.gradle
backend/spring-routie/src/main/java/routie/auth/config/WebMvcConfig.java
backend/spring-routie/src/main/java/routie/docs/config/SwaggerConfig.java

notion에 작성한 API문서와 실제 구현된 API 개수, 경로가 일치하지 않음
작성된 API의 리스트를 빠르게 확인하기 위해 swagger 사용

chore: 신속한 API 리스트 확인을 위해 swagger 추가

---

frontend/src/domains/places/components/AddPlaceModal/AddPlaceModal.tsx
frontend/src/domains/places/components/AddPlaceModal/AddPlaceModalButtons.tsx

- 폼 제출 후 모달이 닫히지 않음
- 상단의 x 버튼과 하단의 닫기 버튼의 기능이 중복됨
- submit 버튼을 눌렀을 때 휴무일 데이터가 전송 타입인 영문 날짜 리스트가 아닌, boolean 리스트로 되어있음
- 폼 제출 시 모달 닫히도록 수정
- UI 중복 요소 제거
- 휴무일 데이터 서버 전송 전 영문 요일 리스트로 변환
close #167

refactor: 폼 제출 시 모달 닫히도록 수정, UI 중복 요소 제거, 휴무일 데이터 서버 전송 전 영문 요일 리스트로 변환

---

backend/spring-routie/src/main/java/routie/routie/controller/dto/response/RoutieReadResponse.java
backend/spring-routie/src/main/java/routie/routie/domain/route/RouteCalculator.java
backend/spring-routie/src/main/java/routie/routie/service/RoutieService.java

루티 상세 조회 기능이 API 명세와 다름
```yml
{
"routieId": 123,
"routiePlaces": [
{
"id": 1001,
"sequence": 1,
"placeId": 10
},
{
"id": 1002,
"sequence": 2,
"placeId": 20
}
]
}
```
응답을 아래와 같이 수정
```
{
"routieId": 123,
"routiePlaces": [
{
"id": 1001,
"sequence": 1,
"placeId": 10
},
{
"id": 1002,
"sequence": 2,
"placeId": 20
}
],
"routes": [
{
"fromSequence": 1,
"toSequence": 2,
"movingStrategy": "DRIVING",
"duration": 30,
"distance": 100
}
]
}
```
close #214

fix: 루티 상세 조회 기능 API 명세에 맞게 수정

---

frontend/src/@common/components/Input/Input.tsx
frontend/src/@common/utils/format.ts
frontend/src/domains/routie/contexts/useRoutieValidateContext.tsx
frontend/src/domains/routie/hooks/useRoutieValidate.ts
frontend/src/layouts/Sidebar/TimeInput.tsx

- 일정 시간을 선택할 때 현재 시간 이전의 날짜도 선택할 수 있는 문제를 발견
- 종료 시간의 경우 하루의 일정을 계획하는 서비스의 목표와 달리 제한 없는 날짜 선택이 가능했던 문제를 발견
- 사용자가 아직 날짜를 선택하지 않았는데 검증 기능을 활성화 하면 바로 검증 요청이 가는 문제를 발견
- 시작 날짜는 현재 시간 기준으로 이전 날짜를 선택할 수 없게 수정
- 종료 시간은 날짜는 시작 날짜와 다르게 적용할 수 없고 시간만 변경할 수 있게 수정
- 아직 날짜를 선택하지 않은 경우 검증 요청을 보내지 않게 수정
- 종료 시간은 시작 시간을 입력하기 전에 입력할 수 없게 제한
https://github.com/user-attachments/assets/6b362c4d-621b-44fb-90d9-4ce7e33c64bc
1. Input 컴포넌트에서 input tag 내장 속성을 사용할 수 없는 문제를 수정했습니다
2. 이후에 루티에 장소가 없는 경우에도 검증 요청을 보내지 않게 수정할 계획입니다
Closes #284

refactor: 일정 시작, 종료 시간 입력 제한 추가

---

frontend/src/layouts/Sidebar/Sidebar.tsx
frontend/src/layouts/Sidebar/TimeInput.tsx

- 동선 검증 기능이 꺼져 있을 때 일정 시간 입력 Input의 영역이 비어있어 공간 활용도가 떨어지는 느낌을 받음
- 동선 검증 기능이 꺼져 있어도 해당 영역은 Input을 보여주고 대신 disabled로 처리한다
Closes #346

refactor: 동선 검증 기능이 꺼져 있어도 input이 UI에서 사라지지 않게 수정

---

frontend/src/domains/places/components/DatePreviewList/DatePreviewList.tsx

- 장소 카드의 휴무일 리스트의 스타일이 깨지는 문제가 있었음
- gap이 지정이 되어있어서 원이 아니였음
- Flex 컴포넌트의 props를  `justifyContent="space-around" width="100%"`로 지정해 내부 요소의 크기에 맞춰 gap이 적용 되도록 함
|변경 전|변경 후|
|---|---|
|<img width="330" height="151" alt="image" src="https://github.com/user-attachments/assets/4aeb477a-c2a3-491b-bb53-55fcba2d6e1b" />|<img width="342" height="181" alt="image" src="https://github.com/user-attachments/assets/5028c111-f0af-4272-9c8c-0ceb2a2cbec4" />|
close #343

chore: 장소 카드 휴무일 리스트를 space-around를 통해 자동 gap으로 수정

---

frontend/src/domains/routie/components/RoutieSection/RoutieSection.tsx
frontend/src/domains/routie/contexts/useRoutieContext.tsx

- 루티 장소 추가 / 삭제 / 수정 시 검증 로직이 제대로 동작하지 않음.
- 루티 검증 API 를 2번씩 호출
- useEffect 내부 불필요한 로직 제거
- 루티 장소 변경 시 불필요한 fetch 로직 제거
https://github.com/user-attachments/assets/2f87d374-4066-424c-bc41-6bca68475231
Closes #360

fix: 루티에서 장소 검증 동작 오류로 개선

---

frontend/src/@common/components/IconButton/IconButton.style.ts
frontend/src/domains/places/components/PlaceCard/PlaceCard.tsx

- 루티 장소는 장소 목록 카드에서 삭제가 되는 사용자의 혼란이 있었습니다.
- 따라서 루티 장소에 들어가있는 장소 목록 카드에서는 선택되었을 경우 버튼을 비활성화 혼란을 줄였습니다. 
https://github.com/user-attachments/assets/05ce82d1-058d-4534-80da-00226fe95628
Closes #381

refactor: 선택된 아이콘 버튼의 포인터 이벤트 비활성화

---

backend/spring-routie/src/main/java/routie/place/controller/dto/response/SearchedPlacesResponse.java
backend/spring-routie/src/main/java/routie/place/domain/SearchedPlace.java
backend/spring-routie/src/test/java/routie/place/domain/PlaceSearcherTest.java

검색된 장소의 id와 DB에 저장된 장소의 id의 변수명이 같아 프론트에서 혼란을 겪음
- 검색된 장소의 id: `searchedPlaceId`
- DB에 저장된 장소의 id: `id`(현행 유지)

refactor: 장소 검색 API 변수명 리팩터링

---

frontend/src/domains/routie/contexts/useRoutieContext.tsx

- 루티에서 장소 순서 변경 시 시간과 거리가 변경되지 않음.
- 루티에서 장소 순서 변경 시 refetch 하도록 개선
https://github.com/user-attachments/assets/e356b81d-a7cc-40ef-90b7-b4c33428f43e
Closes #433

fix: 루티 장소 순서 변경 시 refetch 하도록 수정

---

backend/spring-routie/src/main/java/routie/place/service/PlaceSearchService.java
backend/spring-routie/src/main/java/routie/place/service/PlaceService.java
backend/spring-routie/src/main/java/routie/routie/service/RoutieService.java
backend/spring-routie/src/main/java/routie/routiespace/service/RoutieSpaceService.java

Service 의 클래스 단위에 `@Transactional(readOnly = true)`이 없어 메서드 단위에서 어노테이션을 명시했어야 함.
개발자가 빼먹을 수 있었음.
모든 Service 클래스에서 `@Transactional(readOnly = true)`를 사용하도록 변경.
DB 를 사용하지 않는 public 메서드에 대해 트랜잭션이 열린다는 단점이 있음.
사소한 오버헤드가 존재하지만, 개발자가 어노테이션을 빼먹는 것을 방지하는 것이 더욱 가치있다고 판단.
Closes #439

refactor: 모든 Service 클래스에서 @Transactional(readOnly = true)를 사용하도록 변경

---

frontend/src/domains/routie/components/EmptyRoutieMessage/EmptyRoutieMessage.tsx

루티가 비어있을 때 안내 메세지가 직관적이지 않음
루티가 비어있을 때 안내 메세지를 직관적으로 변경
- 직관적으로 변했나요... 더 좋은 문구가 있다면 추천 받습니다.
close #450

refactor: 빈 루티에 대한 안내 메세지를 직관적으로 변경

---

frontend/src/@common/components/Text/Text.style.ts

장소 카드의 정보의 길이가 긴 경우 줄이 밀려나며 장소 카드의 길이가 유동적으로 변하는 문제 발견
카드 컴포넌트의 가로 크기에 맞추어 정보를 자르고 ... 으로 표현하도록 수정  
Closes #445

refactor: text 컴포넌트에 한 줄 말줄임 기능을 추가함으로써 카드 컴포넌트 개선

---

frontend/src/domains/maps/components/KakaoMap.tsx

지도 첫 화면이 서울 시청 좌표로 되어있어서 사용자가 들어와서 이 좌표가 어디인지 궁금증을 갖게 되는 문제 발견
한국 전역 지도를 보여줌으로써 위의 문제를 해결한다. 
Closes #455

fix: 카카오맵 기본 위치 좌표 수정

---

.github/workflows/setup-open-pr.yml
backend/spring-routie/src/main/java/routie/place/domain/Place.java
backend/spring-routie/src/main/java/routie/place/domain/PlaceClosedDayOfWeek.java
backend/spring-routie/src/main/java/routie/place/service/PlaceService.java
frontend/public/index.html
frontend/src/domains/places/apis/searchPlace.ts
frontend/src/domains/places/components/AddPlaceModal/AddPlaceBasicInfo.tsx
frontend/src/domains/places/components/AddPlaceModal/AddPlaceModal.tsx
frontend/src/domains/places/components/AddPlaceModal/AddPlaceModalButtons.tsx
frontend/src/domains/places/components/AddPlaceModal/AddPlaceValidation.tsx
frontend/src/domains/places/components/AddPlaceModal/AddPlaceVerification.tsx
frontend/src/domains/places/components/PlaceFormSection/AddressInput.tsx
frontend/src/domains/places/components/PlaceFormSection/BusinessHourInputs.tsx
frontend/src/domains/places/components/PlaceFormSection/PlaceForm.types.ts
frontend/src/domains/places/components/PlaceFormSection/PlaceNameInput.tsx
frontend/src/domains/places/components/SearchBox/SearchBox.tsx
frontend/src/domains/places/constants/step.ts
frontend/src/domains/places/hooks/useAddPlaceForm.ts
frontend/src/domains/places/hooks/useFunnel.ts
frontend/src/domains/places/hooks/useSearchPlace.ts
frontend/src/domains/places/types/place.types.ts
frontend/src/domains/places/utils/getValidatedStep.ts

- 하나의 장소 추가 모달에서 전체 입력 값이 있어 사용자 경험이 좋지 않음
- 장소 추가 모달 활성화 시 커서가 모달 밖에 있음
- 장소 검색에 따라 이름, 장소 입력창이 생기면서 모달 높이가 옴직이는 문제
- funnel 적용으로 장소 정보와 검증 정보로 나뉘어 입력 받게 개선
- auto focus 속성으로 모달 활성화 되면 자동으로 포커싱 되도록 개선
- 처음부터 입력창에 장소 이름창과 주소창이 나와있고 placeholder로 검색 안내
https://github.com/user-attachments/assets/c8d2a881-33e0-4259-8f70-4d7e2644850e
Closes #480

feat: 장소 추가 모달에서 관심사에 따라 funnel로 분리

---

frontend/src/@common/components/Input/Input.style.ts
frontend/src/@common/components/Input/Input.tsx
frontend/src/@common/hooks/useSessionStorage.ts
frontend/src/@common/utils/format.ts
frontend/src/@common/utils/sessionStorage.ts
frontend/src/domains/routie/contexts/useRoutieContext.tsx
frontend/src/domains/routie/contexts/useRoutieValidateContext.tsx
frontend/src/domains/routie/hooks/useRoutieValidate.ts
frontend/src/layouts/Sidebar/DateInput.tsx
frontend/src/layouts/Sidebar/Sidebar.tsx
frontend/src/layouts/Sidebar/TimeInput.tsx

- 우리 서비스는 현재 하루에 대한 검증만 진행하는데 시작 & 종료에 날짜를 두 번 입력해야 하는 불편함이 존재했음
- Input 컴포넌트에서 label을 Text 컴포넌트로 설정하지 않았음
- Input의 disabled 색상 & border가 어색하게 느껴짐
- 날짜 입력 & 시간 입력을 분리했습니다
- `Input` 컴포넌트에 `label`을 `Text` 컴포넌트를 사용하게 변경했습니다
- `Input` `disabled`일 때 색상 변경과 `border`를 제거했습니다
- 날짜 & 시간 입력을 분리함에 따라 상태 구조가 변경되어 api 요청을 보낼 때 필요한 형식으로 변환한 파생 상태를 추가했습니다 (`combineDateTime`)
https://github.com/user-attachments/assets/6350819b-840f-4e41-be4a-71c0d88fb430
- 시간 입력에 대한 예외처리가 불완전하여 아예 제거하였습니다 -> 추후 추가 예정
- 제가 놓친 부분이 있다면 따끔한 리뷰 부탁드립니다~
Closes #502

refactor: 일정 날짜, 시간 입력 분리

---

frontend/src/domains/routie/adapters/routieValidationAdapter.ts
frontend/src/domains/routie/apis/routie.ts
frontend/src/domains/routie/types/api.types.ts
frontend/src/domains/routie/types/routie.types.ts

- api 응답을 가공하지 않고 그대로 사용할 경우 백엔드 api 변경에 너무 많은 범위가 영향을 받음
- api 변경에 대한 영향 범위를 최소화하기 위해 중간 계층을 도입한다
- 원래 Place 쪽 도메인에 적용하려 했으나 관련 타입이 조금 꼬여있는 것 같아 적용하지 못했습니다
Closes #548

feat: 루티 검증 api response 중간 계층 도입

---

frontend/src/@common/components/Card/Card.styles.ts
frontend/src/@common/components/Text/Text.style.ts
frontend/src/@common/components/Text/Text.types.ts
frontend/src/domains/maps/components/PlaceOverlayCard.tsx
frontend/src/domains/places/components/PlaceCard/PlaceCard.tsx

ellipsis를 적용시키기 위해서는 텍스트가 들어있어야하는데, Card는 텍스트를 직접 갖고 있는 게 아니라 안에 Flex → Text 컴포넌트와 같은 구조를 갖고 있었기에 말 줄임이 적용되지 않는 문제를 발견
- Card에서 정의된 ellipsis 제거 후 Text에 optional로 추가
- PlaceCard와 PlaceOverlayCard에 적용
Closes #569

fix: Card에서 정의된 한 줄로 말 줄임 코드를 Text 컴포넌트로 이동하도록 수정

---

backend/spring-routie/src/main/java/routie/routie/infrastructure/routecalculator/transit/TransitRouteCalculator.java
backend/spring-routie/src/test/java/routie/routie/controller/RoutieControllerTest.java

- 루티 조회 시 시작 시간이 없는 경우 에러 반환
- 이동 시간을 초로 응답
- 루티 조회 시 시작 시간이 없는 경우 현재 시각을 기반으로 계산
- 이동 시간을 분으로 응답하도록 수정
Closes #603

fix: 대중교통 루티 조회 시작 시간이 없을 시에 현재 시각을 기반으로 계산하도록 수정

---

backend/spring-routie/src/main/java/routie/exception/ErrorCode.java
backend/spring-routie/src/main/java/routie/place/domain/Place.java
backend/spring-routie/src/main/java/routie/routie/domain/routievalidator/ValidationContext.java
backend/spring-routie/src/main/java/routie/routie/domain/timeperiod/TimePeriodCalculator.java
backend/spring-routie/src/main/java/routie/routie/infrastructure/routecalculator/driving/DrivingRouteCalculator.java
backend/spring-routie/src/main/java/routie/routie/infrastructure/routecalculator/transit/TransitRouteCalculator.java
backend/spring-routie/src/main/java/routie/routie/service/RoutieService.java

- 동일한 위경도의 장소를 가진 루티에 대한 조회가 에러를 발생시켰음
- 카카오 API: 2개 장소를 가진 루티에서 출발지와 목적지가 같은 경우 에러 발생
- 카카오 API: 출발지와 목적지가 같은 2개의 장소에 대한 경로를 만드는 경우 -> distance, duration 0으로 응답
- 구글 API: 출발지와 목적지가 같은 경로를 만드는 경우 -> distance, duration 0으로 응답
- 일정 시작 시각이 종료 시작보다 큰 경우, 에러를 반환하도록 수정 
Closes #619

fix: null로 오는 google 응답 핸들링

---

frontend/src/layouts/SideSheet/SideSheet.styles.ts
frontend/src/layouts/SideSheet/SideSheet.tsx
frontend/src/layouts/Sidebar/Sidebar.tsx

- 사이드 시트 border 추가
- 사이드 시트 css(장소목록, tabBaseStyle) 수정
- 사이드바 border 추가
| 닫힌 사이드 시트 | 열린 사이드 시트 |
|----------|----------|
| <img width="561" height="900" alt="스크린샷 2025-08-19 오후 6 24 37" src="https://github.com/user-attachments/assets/4b3d1276-dda7-4a8c-b07f-adc63a0182c5" /> | <img width="942" height="900" alt="image" src="https://github.com/user-attachments/assets/fff255ac-21f7-4359-8425-2b154f9c8063" /> |
Closes #624

refactor: 사이드바 & 시트 외곽선 적용

---

frontend/src/domains/places/components/AddPlaceModal/AddPlaceBasicInfo.tsx
frontend/src/domains/places/constants/step.ts
frontend/src/domains/places/hooks/usePlaceFormValidation.ts
frontend/src/domains/places/utils/getValidatedStep.ts

- 도로명 주소가 없는 경우, 지번 주소가 입력되지 않음.
- 지번에 대한 유효성 검사가 되지 않음.
- 도로명 주소가 없는 경우, 지번 주소가 입력.
- 지번에 대한 유효성 검사 추가
https://github.com/user-attachments/assets/2b7be350-0282-489d-a8e0-110fabd269d3
Closes #609

fix: 도로명 주소가 없는 경우, 지번 주소가 입력되고 다음 입력 스텝으로 이동되도록 수정

---

frontend/src/domains/maps/hooks/useKakaoMapSDK.ts

지도 sdk에 setTimeout을 걸어 약 5초간 불러오고 그 이후에는 에러를 띄우는 로직 구현
https://github.com/user-attachments/assets/8e6df7d9-dc6a-44bb-baa6-bc95f401e3b7
https://github.com/user-attachments/assets/b4b77cb9-0591-4fdf-9933-710b30945647
첫 번째 영상은 정상 작동하는 경우이고, 두 번째 영상은 임의로 sdk 오류를 발생시켜 첨부하였습니다.
5초간 읽어오는 시간을 가진 뒤 sdk를 불러온다면 지도를 보여주고, 불러오지 못한다면 실패했다는 문구를 확인할 수 있습니다.
Closes #612

fix: 지도 sdk에 setTimeOut을 걸어서 잘 읽어오도록 수정

---

frontend/src/domains/maps/components/KakaoMap.tsx
frontend/src/domains/places/components/AddPlaceModal/AddPlaceModal.tsx
frontend/src/layouts/PlaceList/contexts/PlaceListContext.ts
frontend/src/layouts/PlaceList/contexts/PlaceListProvider.tsx
frontend/src/layouts/SideSheet/SideSheet.tsx

- 장소 목록 & 루티 수정이 일어난 경우 항상 모든 마커의 중심 위치로 지도가 이동하는 것이 불편하다는 피드백을 받음
- 마커를 클릭한 경우, 장소를 추가한 경우 해당 마커로 지도 이동
- 첫 렌더링 전체 마커 중심 위치로 이동
- 장소 추가 핸들러 추가
- 자잘한 린트 수정
영상은 사이즈 이슈로 슬랙으로 보냈습니다!
- 새 장소가 추가되었는지 체크하기 위한 상태를 추가했습니다
- 새롭게 추가된 핸들러는 이전 장소와 비교하여 새로운 장소 정보를 보관하고 장소 목록을 다시 받아옵니다
Closes #637

refactor: 장소를 추가하는 상황 & 마커를 클릭한 경우만 지도 이동

---

frontend/src/domains/routieSpace/components/RoutieSpaceName/RoutieSpaceName.style.ts
frontend/src/domains/routieSpace/components/RoutieSpaceName/RoutieSpaceName.tsx
frontend/src/domains/routieSpace/hooks/useRoutieSpaceName.ts

- 루티 스페이스 이름을 수정할 때 버튼의 구분이 없어 수정 중인지 수정이 완료된건지 알 수 없었음
- 빈 값을 요청보낼 수 있었고 그에 피드백이 없었음
- 같은 값을 저장해도 api 요청을 보내고 있었음
- 요청을 보내는 중에 다시 요청을 못 보내게 막는 로직이 없었음
- 아이콘 버튼에서 그냥 버튼으로 변경
- 빈 값인 경우 요청을 보내지 못하게 막고 토스트를 보여주게 수정
- 15자가 넘어간 경우에 요청을 보내지 못하고 input의 error UI를 보여주게 수정 (토스트도 추가)
- 수정을 하지 않으면 요청을 보내지 않게 수정 (이전 값과 비교)
- isLoading 상태를 추가해 요청중에 중복으로 요청을 보내지 못하게 수정
- enter 키로 저장할 수 있게 수정
https://github.com/user-attachments/assets/bffdcf82-49a9-4ea9-82a3-7bc5a8908748
- UI만 수정하려 했는데 에러 UI를 같이 추가하다 보니 로직도 같이 수정하게 되었습니다...🥲
- 원래 20자를 제한으로 두려 했으나 버튼을 추가하고 보니 좁아서 15자로 변경하였습니다
Closes #645

refactor: 루티 스페이스 이름 UI 수정 & 예외 처리 추가

---

frontend/src/@common/hooks/useAsyncLock.ts
frontend/src/@common/hooks/useDebounceAsync.ts
frontend/src/domains/places/components/AddPlaceModal/AddPlaceModal.tsx
frontend/src/domains/places/components/EditPlaceModal/EditPlaceModal.tsx
frontend/src/domains/places/components/PlaceCard/PlaceCard.tsx
frontend/src/domains/routie/components/Route/RoutieRoutes.tsx
frontend/src/domains/routie/contexts/useRoutieContext.tsx
frontend/src/domains/routie/hooks/useRoutieValidate.ts

- 루티 장소 관련 비동기 처리에서 버튼을 빠르게 누르면 중복 요청과 불필요한 연속 호출이 발생
- 검증 토글 비활성화 시에도 invalid place 정보가 초기화되지 않는 문제
- 중복 요청 방지를 위한 `useAsyncLock` 훅 추가 및 적용  
- 해당 훅은 promise 함수를 받아, 함수 실행이 완료되기 전까지는 다른 요청이 실행되지 않도록 하는 훅입니다.
- 적용 대상: AddPlaceModal, EditPlaceModal, PlaceCard 
- (장소 목록에 장소 추가, 수정, 삭제 / 루티에 장소 추가, 삭제 로직은 중복 요청이 발생하면 안 되기 때문에 적용)
- 불필요한 연속 요청 방지를 위한 `useDebouncedAsync` 훅 추가 및 적용  
- 해당 훅은 promise 함수와 지연 시간을 받아, 주어진 시간 안에 새로운 호출이 없을 때만 함수를 실행합니다.  
- 만약 지연 시간 내에 새로운 호출이 들어오면 이전 호출은 취소되고, 마지막 호출만 실행되도록 합니다.  
- 적용 대상: 검증 토글, 이동 수단 선택, 일정 시작, 종료 시간 선택 이후 호출되는 `refetchRoutieData`→ 300ms 디바운스를 적용하여 불필요한 연속 호출 차단 
- (검증 토글, 이동 수단 선택, 일정 시작, 종료 시간 선택을 계속해서 빠르게 클릭하면 불필요하게 연속 요청이 가서 마지막 요청만 처리될 수 있게 적용)
- 서버의 루티 응답이 sequence 로 정렬되어서 오지 않게 변경되어 refetch 후 루티 장소를 sequence 순서대로 sort 해서 상태를 저장하는 로직 …

feat: useAsyncLock / useDebouncedAsync 적용으로 중복,연속 요청 방지

---

frontend/src/domains/maps/components/PlaceOverlayCard.tsx

지도 마커 카드에서 도로명 주소는 잘 보이지만, 지번 주소가 보이지 않는 문제 발견 
- 지도 마커 카드에서 지번 주소도 보이도록 수정
Closes #685

fix: 지도 마커 카드에서 지번 주소도 보이도록 수정

---

frontend/src/@common/components/Spinner/Spinner.style.ts
frontend/src/@common/components/Spinner/Spinner.tsx
frontend/src/@common/components/Spinner/Spinner.types.ts
frontend/src/pages/KakaoAuthCallback/KakaoAuthCallback.tsx
frontend/src/routes/index.tsx

- 로그인 완료 후 토큰을 요청, 리다이렉션 하기 위한 콜백 페이지가 필요
- 로그인 완료 후 토큰을 요청, 리다이렉션 하기 위한 콜백 로딩 페이지 구현
- 공통으로 사용할 수 있는 로딩 스피너 컴포넌트 구현
https://github.com/user-attachments/assets/aac5f5c6-aa51-4a34-b941-059be78a7976
- `KakaoAuthCallback` 페이지에서 로그인 완료 후 토큰 요청 및 리다이렉션을 처리하면 될 듯 합니다.
close #788

feat: 카카오 로그인 콜백 페이지 구현

---

backend/spring-routie/src/main/java/routie/business/authentication/domain/jwt/JwtProcessor.java
backend/spring-routie/src/main/java/routie/business/authentication/ui/argument/AuthenticatedUser.java
backend/spring-routie/src/main/java/routie/business/authentication/ui/argument/config/AuthenticationArgumentConfig.java
backend/spring-routie/src/main/java/routie/business/authentication/ui/argument/interceptor/AuthenticationInterceptor.java
backend/spring-routie/src/main/java/routie/business/authentication/ui/argument/resolver/AuthenticatedUserArgumentResolver.java
backend/spring-routie/src/main/java/routie/business/authentication/ui/jwt/JwtParser.java
backend/spring-routie/src/main/java/routie/global/exception/domain/ErrorCode.java

유저 인증 기능은 구현했으나, 로그인 후 인증 정보(jwt)의 존재 여부를 확인하고 유저를 식별할 수단이 존재하지 않음.
유저 인증을 위한 아키텍처 구현을 통해, HandlerMethod에서 어노테이션을 통한 파라메터 바인딩을 받을 수 있도록 변경.
Closes #802

feat: 인증 아키텍쳐 구현

---

frontend/src/domains/auth/adapters/authAdapter.ts
frontend/src/domains/auth/apis/login.ts
frontend/src/domains/auth/components/LoginModal/LoginModal.tsx
frontend/src/domains/auth/components/UserMenuButton/UserMenuButton.tsx
frontend/src/domains/auth/hooks/useLogout.ts
frontend/src/domains/auth/queries/key.ts
frontend/src/domains/auth/queries/useAuthQuery.ts
frontend/src/domains/auth/types/api.types.ts
frontend/src/domains/auth/types/auth.types.ts
frontend/src/pages/Home/Home.tsx
frontend/src/pages/KakaoAuthCallback/KakaoAuthCallback.tsx

- 각자 구현된 백엔드의 로직과 프론트 로직을 합쳐야 하는 상황
- 카카로 로그인 관련 타입, 어댑터 정의
- 카카로 로그인 관련 API 요청 함수 추가
- 카카로 로그인 관련 쿼리 키 및 훅 추가
- 로그인 시에 변경되는 UI 구현
- 로그인, 로그아웃 기능 구현
https://github.com/user-attachments/assets/a195c4a9-80fc-4377-92a7-4a1a1386ae5a
- 일단 로그아웃 시 토큰 제거 후 홈화면으로 리다이렉트 되도록 구현하였습니다. 이건 추후에 논의를 다시 해봐야 할 것 같습니다.
- 이어서 닉네임 받아오는 로직 추가하면 될 것 같습니다.

feat: 카카오 로그인 API 연동 및 로그인, 로그아웃 기능 구현

---

backend/spring-routie/src/main/java/routie/business/routiespace/application/RoutieSpaceService.java
backend/spring-routie/src/main/java/routie/business/routiespace/domain/RoutieSpaceRepository.java
backend/spring-routie/src/main/java/routie/business/routiespace/ui/dto/response/RoutieSpaceListResponse.java
backend/spring-routie/src/main/java/routie/business/routiespace/ui/v1/RoutieSpaceControllerV1.java
backend/spring-routie/src/test/java/routie/business/routiespace/ui/v1/RoutieSpaceControllerV1Test.java

- 내 루티 스페이스 목록을 조회할 수 있는 API 추가
- 헤더의 Access Token을 기반으로 본인의 루티 스페이스만 조회
closes #835

feat: 내 루티 스페이스 목록 조회 API 추가

---

backend/spring-routie/src/main/java/routie/business/routiespace/application/RoutieSpaceService.java
backend/spring-routie/src/main/java/routie/business/routiespace/ui/v1/RoutieSpaceControllerV1.java
backend/spring-routie/src/test/java/routie/business/routiespace/ui/v1/RoutieSpaceControllerV1Test.java

- 사용자가 본인의 루티 스페이스를 삭제할 수 있는 API 추가
- 헤더의 Access Token을 기반으로 본인의 루티 스페이스만 삭제 가능
closes #834

feat: 내 루티 스페이스 삭제 API 추가

---

backend/spring-routie/src/main/java/routie/business/like/domain/PlaceLikeRepository.java
backend/spring-routie/src/main/java/routie/business/place/application/PlaceService.java
backend/spring-routie/src/test/java/routie/business/place/ui/v1/PlaceControllerV1Test.java

- 좋아요가 눌려있는 경우 장소 삭제가 안됨
- 장소 삭제 시 좋아요도 같이 삭제함
closes #849

fix: 장소 삭제 시 좋아요도 같이 삭제

---

backend/spring-routie/src/main/java/routie/business/like/domain/PlaceLikeRepository.java
backend/spring-routie/src/main/java/routie/business/routiespace/application/RoutieSpaceService.java
backend/spring-routie/src/test/java/routie/business/routiespace/ui/v1/RoutieSpaceControllerV1Test.java

- 루티 스페이스 삭제 시 오류 발생
- 관련된 좋아요 삭제로 해결
closes #854

fix: 루티 스페이스 삭제 시 장소에 관련된 좋아요 삭제

---

backend/spring-routie/src/main/java/routie/business/routie/domain/Routie.java
backend/spring-routie/src/main/java/routie/business/routie/domain/RoutiePlace.java

루티 스페이스를 제거할 수 없었음.
```
[UNEXPECTED] could not execute statement [Column 'place_id' cannot be null] [update routie_places set created_at=?,place_id=?,sequence=? where id=?]; SQL [update routie_places set created_at=?,place_id=?,sequence=? where id=?]; constraint [null]
```
양방향 매핑 적용으로 긴급 해결 (과정은 추후 작성)
Closes #858

fix: 루티 스페이스를 삭제할 수 없는 문제 해결
